//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaTahvilAlphaV1.Model.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbBorsaTahvilEntities1 : DbContext
    {
        public DbBorsaTahvilEntities1()
            : base("name=DbBorsaTahvilEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblBotBilgi> tblBotBilgi { get; set; }
        public virtual DbSet<tblKrediKarti> tblKrediKarti { get; set; }
        public virtual DbSet<tblKullanici> tblKullanici { get; set; }
        public virtual DbSet<tblMakale> tblMakale { get; set; }
        public virtual DbSet<tblManuelIslem> tblManuelIslem { get; set; }
        public virtual DbSet<tblPost> tblPost { get; set; }
        public virtual DbSet<tblYetki> tblYetki { get; set; }
        public virtual DbSet<CryptoPara> CryptoPara { get; set; }
        public virtual DbSet<KriptoSatimİslem> KriptoSatimİslem { get; set; }
        public virtual DbSet<tblDestek> tblDestek { get; set; }
    }
}
