//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaTahvilAlphaV1.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblKullanici()
        {
            this.tblBotBilgi = new HashSet<tblBotBilgi>();
            this.tblManuelIslem = new HashSet<tblManuelIslem>();
            this.KriptoSatimİslem = new HashSet<KriptoSatimİslem>();
            this.tblPost = new HashSet<tblPost>();
            this.tblDestek = new HashSet<tblDestek>();
        }
    
        public int Id { get; set; }
        public string KullaniciAdi { get; set; }
        public string KullaniciSoyadi { get; set; }
        public string KullaniciEmail { get; set; }
        public string KullaniciNickName { get; set; }
        public string KullaniciParola { get; set; }
        public Nullable<bool> YasakliKullanicilar { get; set; }
        public Nullable<decimal> KullaniciCuzdanPara { get; set; }
        public Nullable<int> KrediKartId { get; set; }
        public int Yetki { get; set; }
        public Nullable<double> Derece { get; set; }
        public Nullable<int> DereceKisiSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBotBilgi> tblBotBilgi { get; set; }
        public virtual tblKrediKarti tblKrediKarti { get; set; }
        public virtual tblYetki tblYetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManuelIslem> tblManuelIslem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KriptoSatimİslem> KriptoSatimİslem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPost> tblPost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDestek> tblDestek { get; set; }
    }
}
