//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaTahvilAlphaV1.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManuelIslem
    {
        public int Id { get; set; }
        public string IslemIsim { get; set; }
        public int AlinanMiktar { get; set; }
        public int KullaniciId { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
