//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaTahvilAlphaV1.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMakale
    {
        public int Id { get; set; }
        public string Baslik { get; set; }
        public string MakaleGovde { get; set; }
        public byte[] Resim { get; set; }
        public bool Durum { get; set; }
    }
}
