//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BorsaTahvilAlphaV1.Model.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        public int Id { get; set; }
        public string Post_isim { get; set; }
        public string Post_aciklama { get; set; }
        public Nullable<int> Post_gorulme { get; set; }
        public Nullable<int> Post_paylasim { get; set; }
        public Nullable<int> Post_yorum_sayisi { get; set; }
        public int KullaniciId { get; set; }
        public bool Durum { get; set; }
    
        public virtual tblKullanici tblKullanici { get; set; }
    }
}
